version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    environment:
      ND_LOGLEVEL: info
    volumes:
      - "${USED_DOCKER_DATA}/navidrome/data:/data"
      - "${USED_MUSIC_PATH}:/music:ro"
networks:
  default:
    name: nginx_default   # Port 4533 (web)
    external: true