version: "2.1"
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: "unless-stopped"
    networks:
      - nginx_default
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      -${USED_DOCKER_DATA}/jellyfin/jellyfin_config:/config
      -${USED_DOCKER_DATA}/jellyfin/jellyfin_cache:/cache
      -${USED_MEDIA_PATH}/Shows:/data/tvshows
      -${USED_MEDIA_PATH}/Movies:/data/movies
      -${USED_MEDIA_PATH}/Porn:/data/porn
      -${USED_MEDIA_PATH}/Temp:/data/temp
      -${USED_MEDIA_PATH}/Media:/data/media