version: "2.1"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ${USED_DOCKER_DATA}/freshrss/config:/config
    restart: unless-stopped
networks:
  default:
    name: nginx_default # Port 80 (web)
    external: true